apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system


#Google GCP Error:
###
#helm reset
#kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
#helm init --service-account tiller --upgrade

### Create a NGINX Controller
# kubectl apply -f helm-rbac.yaml
# helm init
# helm search
# helm install stable/nginx-ingress --name version-ingress-controller --namespace wildfire --set rbac.create=true 
